name: CI

on:
  push:
    paths:
      - '**/*.cc'
      - '**/*.cpp'
      - '**/*.hpp'
      - 'CMakeLists.txt'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: iantorres/boosted:1.87.0-debug

    steps:
      - uses: actions/checkout@v4

      - name: Configure with coverage flags
        run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Generate coverage report
        run: |
          lcov --directory build --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true